insert into movie (id, description, director_birth_date, director_name, director_surname, duration, genre, release_date,
                   score, thumbnail, title)
values (1,
        'In a post-apocalyptic world, a family is forced to live in silence while hiding from monsters with ultra-sensitive hearing.',
        '1979-10-20', 'John', 'Krasinski', 5400000000000, 'HORROR', '2018-04-13', 7.50,
        'https://thumbnails.com/quiet-place', 'A Quiet Place'),
       (2,
        'An elite Navy SEAL, goes on a path to avenge his wife''s murder only to find himself inside of a larger conspiracy.',
        '1966-05-04', 'Stefano', 'Sollima', 6540000000000, 'ACTION', '2021-02-25', 5.80,
        'https://thumbnails.com/without-remorse', 'Tom Clancy Without Remorse'),
       (3,
        'An organized crime dynasty''s aging patriarch transfers control of his clandestine empire to his reluctant son.',
        '1939-04-07', 'Francis', 'Copolla', 10500000000000, 'ACTION', '1972-12-31', 9.20,
        'https://thumbnails.com/godfather', 'The Godfather'),
       (4,
        'When a congressional aide is killed, a Washington, D.C. journalist starts investigating the case involving the Representative, his old college friend.',
        '1967-10-28', 'Kevin', 'Macdonald', 7620000000000, 'THRILLER', '2009-04-17', 7.10,
        'https://thumbnails.com/state-of-play', 'State of Play'),
       (5,
        'In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner''s vengeful plans for the same.',
        '1963-03-27', 'Quentin', 'Tarantino', 9180000000000, 'ACTION', '2009-09-11', 8.30,
        'https://thumbnails.com/inglorious-basterds', 'Inglourious Basterds'),
       (6,
        'In 1985 where former superheroes exist, the murder of a colleague sends active vigilante Rorschach into his own sprawling investigation, uncovering something that could completely change the course of history as we know it.',
        '1966-03-01', 'Zack', 'Snyder', 9720000000000, 'ACTION', '2009-02-23', 7.60,
        'https://thumbnails.com/watchmen','Watchmen'),
       (7,
        'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.',
        '1962-08-28', 'David', 'Fincher', 8340000000000, 'THRILLER', '2009-02-11',8.80,
        'https://thumbnails.com/fight-club', 'Fight Club'),
       (8,
        'A pragmatic paleontologist visiting an almost complete theme park is tasked with protecting a couple of kids after a power failure causes the park''s cloned dinosaurs to run loose.',
        '1946-12-18', 'Steven', 'Spielberg', 7620000000000, 'ACTION', '1993-06-09', 8.10,
        'https://thumbnails.com/jurassic-park', 'Jurassic Park'),
       (9,
        'The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.',
        '1951-05-14', 'Robert', 'Zemeckis', 8520000000000, 'COMEDY', '1994-11-04', 8.80,
        'https://thumbnails.com/forrest-gump', 'Forrest Gump'),
       (10,
        'With his wife''s disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it''s suspected that he may not be innocent.',
        '1962-08-28', 'David', 'Fincher', 8940000000000, 'THRILLER', '2014-10-10', 8.10,
        'https://thumbnails.com/gone-girl', 'Gone Girl');