POST http://localhost:8080/api/a-spots
Content-Type: application/json

{
  "size": "SMALL",
  "movie": {
    "id": 7
  }
}

###
POST http://localhost:8080/api/a-spots
Content-Type: application/json

{
  "size": "SMALL",
  "movie": {
    "id": 99
  }
}

###
PUT http://localhost:8080/api/a-spots/11/movies/4

###
POST http://localhost:8080/api/screens
Content-Type: application/json

{
  "title": "Popular new hits",
  "aspot": {
    "id": 11
  }
}

###
POST http://localhost:8080/api/screens
Content-Type: application/json

{
  "title": "Classic great movies",
  "aspot": {
    "size": "LARGE",
    "movie": {
      "id": 3
    }
  }
}

###
POST http://localhost:8080/api/screens
Content-Type: application/json

{
  "title": "Movies that never exists",
  "aspot": {
    "size": "LARGE",
    "movie": {
      "id": 99
    }
  }
}
###
DELETE http://localhost:8080/api/screens/12