PUT http://localhost:8080/api/lanes/13/movies
Content-Type: application/json

{
  "movieIds": [2, 4, 6]
}

###
DELETE http://localhost:8080/api/lanes/13/movies/2

###
GET http://localhost:8080/api/screens/12/lanes