GET http://localhost:8080/api/series

###
POST http://localhost:8080/api/series
Content-Type: application/json

{
  "title": "And Quiet Flows the Don",
  "description": "Grigory Panteleevich Melekhov, is a promising young soldier who falls in love with Aksinia, the wife of Stepan Astakhov, a family friend. Stepan regularly beats her and there is no love between them.",
  "genre": "THRILLER",
  "releaseDate": "1933-02-13",
  "numberOfEpisodes": 3,
  "score": "6.3",
  "thumbnail": "https://thumbnails.com/quiet-flows-the-don"
}

###
DELETE http://localhost:8080/api/series/11

###
GET http://localhost:8080/api/positions?title=Quiet