GET http://localhost:8080/api/positions?title=Quiet

###
GET http://localhost:8080/api/positions?genre=THRILLER

###
GET http://localhost:8080/api/positions?minDate=2010-01-01

###
GET http://localhost:8080/api/positions?maxDate=2010-01-01

###
GET http://localhost:8080/api/positions?minScore=7.5

###
GET http://localhost:8080/api/positions?maxScore=7.5

###
GET http://localhost:8080/api/positions?title=Quiet&genre=HORROR&maxScore=9.0&minScore=1.0&minDate=1900-01-01&maxDate=2021-01-01